import type { BookingStatus } from '@/lib/constants';

/**
 * The booking state machine.
 *
 * Transitions:
 *   pending → confirmed → active → completed
 *   pending → cancelled (driver or lender cancels)
 *   active → disputed (issue raised)
 *   completed → disputed (issue raised within 24h)
 */

export interface BaseBooking {
  id: string;
  chargerId: string;
  driverId: string;
  lenderId: string;
  scheduledStart: Date;
  scheduledEnd: Date;
  confirmationCode: string;
  createdAt: Date;
}

export type Booking = BaseBooking & {
  status: BookingStatus;
  actualStart: Date | null;
  actualEnd: Date | null;
  kwhDelivered: number | null;
  cancellationReason: string | null;
};

/**
 * Input shape when creating a new booking.
 * The fields generated by the server (id, code, etc.) are omitted.
 */
export interface CreateBookingInput {
  chargerId: string;
  scheduledStart: string; // ISO timestamp
  scheduledEnd: string;
  estimatedKwh: number;
}
